TRAIN:
  ENABLE: True
  DATASET: EpicKitchens
  BATCH_SIZE: 4
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH_ASF: weights/asf/SLOWFAST_EPIC.pyth
  CHECKPOINT_FILE_PATH_VSF: weights/SLOWFAST_EK100.pkl
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
  FINETUNE_VSF: False

DATA:
  INPUT_CHANNEL_NUM_ASF: [1, 1]
  INPUT_CHANNEL_NUM_VSF: [3, 3] # TODO: Fix with right values

  TRAIN_JITTER_SCALES_VSF: [256, 320]
  TRAIN_CROP_SIZE_VSF: 224
  TEST_CROP_SIZE_VSF: 256

ASF:
  AUDIO_DATA:
    CLIP_SECS: 1.999
    NUM_FRAMES: 400

  SLOWFAST:
    ALPHA: 4
    BETA_INV: 8
    FUSION_CONV_CHANNEL_RATIO: 2
    FUSION_KERNEL_SZ: 7

  RESNET:
    ZERO_INIT_FINAL_BN: True
    WIDTH_PER_GROUP: 64
    NUM_GROUPS: 1
    DEPTH: 50
    TRANS_FUNC: bottleneck_transform
    STRIDE_1X1: False
    NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
    FREQUENCY_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
    FREQUENCY_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

  MODEL:
    NUM_CLASSES: [97, 300]
    ARCH: slowfast
    MODEL_NAME: AudioSlowFast
    LOSS_FUNC: cross_entropy
    DROPOUT_RATE: 0.5

  AUGMENT:
    ENABLE: False
    BALANCE: False
    FACTOR: 1.0001

VSF:
  SLOWFAST:
    ALPHA: 4
    BETA_INV: 8
    FUSION_CONV_CHANNEL_RATIO: 2
    FUSION_KERNEL_SZ: 7

  RESNET:
    ZERO_INIT_FINAL_BN: True
    WIDTH_PER_GROUP: 64
    NUM_GROUPS: 1
    DEPTH: 50
    TRANS_FUNC: bottleneck_transform
    STRIDE_1X1: False
    NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
    SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
    SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

  NONLOCAL:
    LOCATION: [[[], []], [[], []], [[], []], [[], []]]
    GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
    INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

TEST:
  ENABLE: False
  DATASET: EpicKitchens
  BATCH_SIZE: 8
  NUM_SPATIAL_CROPS_VSF: 1

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

EPICKITCHENS:
  TRAIN_PLUS_VAL: False
  TRAIN_LIST: data/epic-kitchens-100-annotations/EPIC_100_train.pkl
  VAL_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  TEST_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  VISUAL_DATA_DIR: /rgb_frames
  AUDIO_DATA_FILE: /scratch/work/ptg/EPIC-KITCHENS/EPIC_audio.hdf5

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: runs/mm-sf-test
WANDB:
  ENABLE: True
